In [1]:
import numpy as np
import pandas as pd

In [2]:
Train_fashion = pd.read_csv("C:\\Users\\Mega Store\\OneDrive\\Desktop\\fashion-mnist_train.csv")

In [3]:
Train_fashion

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,1,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,8,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
x_train = Train_fashion.drop(columns = {"label"}).T
y_train = np.array(Train_fashion["label"])

In [5]:
m =x_train.shape[1]
m

60000

In [6]:
x_train.shape[0]

784

In [7]:
len(y_train)

60000

In [8]:
def initialize_parameters(n_x, n_h, n_y):

    W1 = np.random.randn(n_h,n_x)* 0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h) * 0.01
    b2 = np.zeros((n_y,1))
    

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [9]:
def activation_function(Z):
      return np.tanh(Z)

In [10]:
def soft_max(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

In [11]:
def forward_propagation(X, parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    

    Z1 = np.dot(W1,X) + b1
    A1 = activation_function(Z1)
    Z2 = np.dot(W2,A1) + b2
    A2 = soft_max(Z2)
    
    output = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2,output

In [12]:

def compute_cost(A2, Y):
    
    m = x_train.shape[1]

    logprobs = np.multiply(np.log(A2),Y) + np.multiply(np.log(1 - A2),1 - Y)
    cost = - np.sum(logprobs) * (1 / m) 
    

    
    cost = float(np.squeeze(cost)) 
    return cost

In [13]:

def backward_propagation(parameters, output, X, Y):
    
    m = X.shape[1]
    
    
    W1 = parameters["W1"]
    W2 = parameters["W2"]
    
    
    A1 = output["A1"]
    A2 = output["A2"]
    
    
    dZ2= A2 - Y
    dW2 = 1 / m *(np.dot(dZ2,A1.T))
    db2 = 1 / m *(np.sum(dZ2,axis = 1,keepdims = True))
    dZ1 = np.dot(W2.T,dZ2) * (1 - np.power(A1, 2))
    dW1 = 1 / m *(np.dot(dZ1,X.T))
    db1 = 1 / m *(np.sum(dZ1,axis = 1,keepdims = True))
        
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [14]:
def update_parameters(parameters, grads, alpha = 1.2):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    
    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]  
    
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    

    return parameters

In [15]:
def nn_model(X, Y, n_h, num_iterations = 100, print_cost=False):
    
    np.random.seed(3)
    n_x = x_train.shape[0]
    n_y = 10
    
    parameters = initialize_parameters(n_x,n_h,n_y)
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    for i in range(0, num_iterations):
         
        
        A2, output = forward_propagation(X,parameters)
        cost = compute_cost(A2, Y)
        grads = backward_propagation(parameters, output, X, Y)
        parameters = update_parameters(parameters, grads)

 


        
      
        if print_cost and i % 1000 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))

    return parameters

In [16]:
def predict(parameters,X):
    A2, output = forward_propagation(X,parameters)
    predictions =np.argmax(A2, 0)

    return predictions

In [17]:
parameters = nn_model(x_train, y_train, n_h = 4, num_iterations = 100, print_cost=True)

Cost after iteration 0: 99.937040

<ipython-input-10-d8701b787d6c>:2: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-10-d8701b787d6c>:2: RuntimeWarning: invalid value encountered in true_divide
  A = np.exp(Z) / sum(np.exp(Z))

In [18]:
test_fashion =pd.read_csv("C:\\Users\\Mega Store\\OneDrive\\Desktop\\fashion-mnist_test.csv")

In [19]:
x_test = Train_fashion.drop(columns = {"label"}).T
y_test= np.array(Train_fashion["label"])

In [20]:
parameters = nn_model(x_test, y_test, n_h = 4, num_iterations = 100, print_cost=True)

Cost after iteration 0: 99.937040

<ipython-input-10-d8701b787d6c>:2: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-10-d8701b787d6c>:2: RuntimeWarning: invalid value encountered in true_divide
  A = np.exp(Z) / sum(np.exp(Z))